spring:
  application:
    name: BlogProject

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_HOST}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

mybatis:
  type-aliases-package: org.example.blogproject.dto
  mapper-locations: classpath:mapper/*.xml